### PR TITLE
feat(logger): implement slog.Handler

### PR DESCRIPTION
**Pull request by aymanbagabas**
Uses x/exp/slog for go1.19 and go1.20 and log/slog for >go1.21.
Upgrades the minimum go version to go1.19

Example:
```go
package main

import (
	"fmt"
	"time"

	"github.com/charmbracelet/log"
	"golang.org/x/exp/slog"
)

func main() {
	log.SetTimeFormat(time.Kitchen)
	log.SetLevel(log.DebugLevel)
	log.SetReportCaller(true)
	logger := slog.New(log.Default())
	logger.Debug("This is a debug message")
	logger.Info("This is an info message with attributes", "key", "value")
	sub := logger.With("attr", "value")
	sub.Warn("This is a warning message from a sublogger")
	group := sub.WithGroup("subgroup")
	group.Error("This is an error message from a group", fmt.Errorf("this is an error"))
}
```

Output:
```sh
12:54PM DEBU <app/main.go:16> This is a debug message
12:54PM INFO <app/main.go:17> This is an info message with attributes key=value
12:54PM WARN <app/main.go:19> This is a warning message from a sublogger attr=value
12:54PM ERRO <app/main.go:21> subgroup: This is an error message from a subgroup attr=value err="this is an error"
```

Fixes: https://github.com/charmbracelet/log/issues/8

### CODE REVIEW

**Comment by owenthereal** [comment]
👋 Was looking for bridging with `slog`. Any update?

**Comment by bashbunni** [comment]
@owenthereal I believe we're just waiting for slog to be merged into the language as the API may change in the meantime. https://github.com/golang/go/issues/56345 (I think that's the right issue iirc)

Will be quick to merge once that's all up to date!

**Comment by EwenQuim** [comment]
Now that 1.21 released `log/slog`, is it possible to make this lib compatible ? It looks very pretty, better than the default slog TextHandler

**Comment by jamietanna** [comment]
Is there anything I can do to help get #74 merged in with this / with this PR released?

**Comment by jamietanna** [comment]
Ooh interesting!

Sure thing, I was thinking of only supporting as early as Go 1.20, as it's the earliest version of Go that the Go team support, but happy to add `exp/slog`, that's a good idea if we want to support old versions :raised_hands:

**Comment by jamietanna** [comment]
Thanks for carrying on with this I'd remembered yesterday I needed to get back to my PR, but appreciate you doing it 🙌🏽

**Review by caarlos0 — COMMENTED** [review]
LGTM

It looks like it might be a breaking change though, as the JSON keys for some fields changed.

**Comment by aymanbagabas** [comment]
> It looks like it might be a breaking change though, as the JSON keys for some fields changed.

Yes, that's correct, there will be breaking changes in the next release

**Review by dezren39 — APPROVED** [review]

**Pull request merged**
