### PR TITLE
feat(calleroffset): added option to config custom caller offset

### PR DESCRIPTION
**Pull request by waffle69691337**

### CODE REVIEW

**Comment by waffle69691337** [comment]
@aymanbagabas hey, first pr I ever created on open source, project.
really love this logger and I would like to add this functionality to it :)

**Comment by aymanbagabas** [comment]
Hi @waffle69691337 what's your use case for this?

**Comment by waffle69691337** [comment]
> Hi @waffle69691337 what's your use case for this?

We wrap the logger, with our own logger, so currently the caller always contains the logger.go file

**Comment by aymanbagabas** [comment]
@waffle69691337 Thank you for your contribution. This is now part of [v0.2.2](https://github.com/charmbracelet/log/releases/tag/v0.2.2)

**Pull request merged**
